### PR TITLE
cleanup and minor fixes

### PR DESCRIPTION
**Pull request by burtbeckwith**

### CODE REVIEW

**Comment by brian428** [comment]
Thanks a lot, Burt! Just curious: does this have anything to do with the Grails/Resources issue where the applicationContext is null in the onChange event handler? Or is this just cleanup help since you couldn't bear seeing my shoddy first-timer attempt at a public Grails plugin? ;-)

**Comment by brian428** [comment]
Ah, nm, I see you pushed a fix to Grails as well (https://github.com/grails/grails-core/commit/280fa80dfeb83455d303409abbcfaf3b1e5968b7). You probably just forked my plugin to test the conditions for the bug, and couldn't resist fixing some of my mistakes while you were in there. Thanks again!

**Comment by burtbeckwith** [comment]
Right, I was testing your plugin and hadn't used it before, but the containsKey checks were causing the files to be ignored. While I was there I did my standard cleanup. Nothing too egregious, other than all of those braces dangling on the next line instead of at the end of the current line where they belong :)

**Comment by brian428** [comment]
Hah, the "where do the braces belong" Holy War! I've gone back and forth on whether I prefer braces on the next line or the same line. If it makes you feel better, I've recently vacillated back to preferring them on the same line. :-)

**Pull request merged**
