### PR TITLE
can force using Rhino via grails config file

### PR DESCRIPTION
**Pull request by pawelByszewski**
Whe you have installed  Node and Rhino, now you can force using Rhino via Config.groovy.
Example form Config.groovy

'coffeescript-compiler' {

```
pluginConfig {
    ...................
    forceRhino = true
}

appSource {
   .............
}
```

}

### CODE REVIEW

**Comment by brian428** [comment]
Just wondering why you'd WANT to use the Rhino compiler if you already have the Node compiler running?

**Comment by pawelByszewski** [comment]
There are tiny differences between Rhino and Node. I have started participate in project where everyone are using Rhino and in my case was compilation problem that disappeared when I force Rhino. Moreover you have already done everything to enable that configuration. So why keep it hidden from end user?

**Comment by brian428** [comment]
Oh I wasn't so much saying you shouldn't do it, I was just curious as to why you'd want to. That makes sense.

**Comment by brian428** [comment]
I'll publish a new release of the plugin shortly. Thanks.

**Comment by pawelByszewski** [comment]
I have post a note about your plugin and my contribution. I hope you don't mind?
http://newbility.blogspot.com/2013/07/grails-coffeescript-plugin.html

**Comment by brian428** [comment]
Sure! I still have to package up the new version and push it to the Grails
plugin repository too. I'll try to do that today or tomorrow.

Thanks,

Brian

**Comment by brian428** [comment]
Just to update, 0.9.3 has been released to the Grails plugin repository. Thanks!

**Pull request merged**
