### PR TITLE
Resolving issue #4

### PR DESCRIPTION
**Pull request by ctoestreich**
Seems like I was able to clear up the issue using Rhino on 2.2.0 and 2.2.1.  I also changed the purgeJS to false by default and added *.js filter to this as it deleting my *.coffee files in the js dir again.  Did some additional code cleanup to make Node tests ignore when node isn't installed.

### CODE REVIEW

**Comment by ctoestreich** [comment]
Make sure you test before taking my word that this works :)

**Comment by ctoestreich** [comment]
Make sure that when using grails 2.2+ you set `legacyResolve true` in the RhinoTest BuildConfig.groovy when using installing the plugin as a ZIP from the lib folder or it won't resolve the wro4j deps.  (Issue/feature with grails 2.2)

**Comment by brian428** [comment]
Cool, thanks! I'll try to give this a check tonight!

**Comment by brian428** [comment]
Christian, sorry to say that after merging in your updates, cleaning, and recompiling, and running test-app on the plugin project, I'm seeing the same "null" errors on Grails 2.2. I know it's long, but just so you can see what I'm seeing I'll paste the test log at the end of this post.

It took a bit of time to merge your changes since it looks like you were working against the 0.7 version. Once I resolved the conflicts (mainly just accepting your version), I noticed that you (inadvertently?) deleted everything in the PluginTestWithNodeTests and PluginTestWithRhinoTests. I kept most of that from my version.

So, not sure what might be going on if things are ok for you on Grails 2.2. Could you rebase on top of the current master (0.8.1) and make sure the two test classes keep their tests, and give it another run to confirm whether or not things still pass on your end?

Thanks. Long test output follows...not sure if it will matter but I just want to make sure you see what I'm seeing. The errors in tests that check for invalid .coffee files are expected, but not the rest obviously.

```
C:\Developer\Java\jdks\64bit\jdk_7_u10\bin\java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:63942,suspend=y,server=n -Dgrails.home=C:\Developer\Java\common\grails-2.2.0 -Dbase.dir=C:\Developer\Projects\Personal\coffeescript-compiler -Dtools.jar=C:\Developer\Java\jdks\64bit\jdk_7_u10\lib\tools.jar -Dgroovy.starter.conf=C:\Developer\Java\common\grails-2.2.0/conf/groovy-starter.conf -Xmx768M -Xms768M -XX:MaxPermSize=256m -XX:PermSize=256m -Djline.WindowsTerminal.directConsole=false -Dgrails.build.listeners=org.jetbrains.groovy.grails.rt.GrailsIdeaTestListener -javaagent:C:\Users\Administrator\.IntelliJIdea12\system\groovyHotSwap\gragent.jar -Dfile.encoding=UTF-8 -classpath "C:\Developer\Java\common\grails-2.2.0\lib\org.codehaus.groovy\groovy-all\jars\groovy-all-2.0.5.jar;C:\Developer\Java\common\grails-2.2.0\dist\grails-bootstrap-2.2.0.jar;C:\Developer\IDE\IntelliJ IDEA 12.0.2\lib\idea_rt.jar" org.codehaus.groovy.grails.cli.support.GrailsStarter --main org.codehaus.groovy.grails.cli.GrailsScriptRunner --conf C:\Developer\Java\common\grails-2.2.0/conf/groovy-starter.conf --classpath "C:\Developer\Projects\Personal\coffeescript-compiler\out\test\test-coffeescript-compiler-grailsPlugins;C:\Developer\Projects\Personal\coffeescript-compiler\out\production\test-coffeescript-compiler-grailsPlugins;C:\Developer\IDE\IntelliJ IDEA 12.0.2\lib\junit-4.10.jar;C:\Developer\IDE\IntelliJ IDEA 12.0.2\plugins\Grails\lib\grails-rt.jar" "test-app --stacktrace"
Testing started at 12:05 AM ...
Connected to the target VM, address: '127.0.0.1:63942', transport: 'socket'

| Loading Grails 2.2.0
| Configuring classpath
| Configuring classpath.
| Environment set to test
| Environment set to test.
| Environment set to test..
| Environment set to test...
| Environment set to test....
| Environment set to test.....
| Packaging Grails application
| Packaging Grails application.
| Packaging Grails application..
| Packaging Grails application...
| Packaging Grails application....
| Packaging Grails application.....
| Packaging Grails application
| Packaging Grails application.
| Packaging Grails application..
| Packaging Grails application...
| Packaging Grails application....
| Packaging Grails application.....
| Compiling 4 source files
| Compiling 4 source files.
| Running 14 integration tests...
| Running 14 integration tests... 1 of 14
--Output from testDefaultConfig--
| Running 14 integration tests... 2 of 14
--Output from testWithConfig--
| Running 14 integration tests... 3 of 14
--Output from testCoffeeSourceTree--
| Running 14 integration tests... 4 of 14
--Output from testInvalidCoffeeScript--
| Error 2013-03-05 00:05:18,603 [main] ERROR processor.NodeCoffeeScriptProcessor  - exitStatus: 1
| Error 2013-03-05 00:05:18,627 [main] ERROR processor.NodeCoffeeScriptProcessor  - Error in CoffeeScript: 
SyntaxError: In src\coffee\myBadFile.coffee, unmatched ) on line 3
    at SyntaxError (unknown source)
    at Lexer.exports.Lexer.Lexer.error (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:682:13)
    at Lexer.exports.Lexer.Lexer.pair (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:634:16)
    at Lexer.exports.Lexer.Lexer.literalToken (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:456:16)
    at Lexer.exports.Lexer.Lexer.tokenize (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:33:220)
    at Object.exports.compile.compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\coffee-script.js:47:32)
    at compileScript (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:182:33)
    at fs.stat.notSources.(anonymous function) (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:152:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)

Message: Error in CoffeeScript: 
SyntaxError: In src\coffee\myBadFile.coffee, unmatched ) on line 3
    at SyntaxError (unknown source)
    at Lexer.exports.Lexer.Lexer.error (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:682:13)
    at Lexer.exports.Lexer.Lexer.pair (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:634:16)
    at Lexer.exports.Lexer.Lexer.literalToken (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:456:16)
    at Lexer.exports.Lexer.Lexer.tokenize (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:33:220)
    at Object.exports.compile.compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\coffee-script.js:47:32)
    at compileScript (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:182:33)
    at fs.stat.notSources.(anonymous function) (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:152:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)

   Line | Method
->> 101 | processData             in org.grails.plugins.coffee.compiler.processor.NodeCoffeeScriptProcessor
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    69 | process                 in     ''
|    77 | process . . . . . . . . in org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor
|    68 | compileFile             in org.grails.plugins.coffee.compiler.CoffeeCompiler
|    67 | compileFileFromConfig . in org.grails.plugins.coffee.compiler.CoffeeCompilerManager
|   161 | testInvalidCoffeeScript in coffeescript.compiler.PluginTestWithNodeTests
|    45 | runReflectiveCall . . . in org.junit.runners.model.FrameworkMethod$1
|    15 | run                     in org.junit.internal.runners.model.ReflectiveCallable
|    42 | invokeExplosively . . . in org.junit.runners.model.FrameworkMethod
|    20 | evaluate                in org.junit.internal.runners.statements.InvokeMethod
|    22 | evaluate . . . . . . .  in org.junit.internal.runners.statements.ExpectException
|    28 | evaluate                in org.junit.internal.runners.statements.RunBefores
|    30 | evaluate . . . . . . .  in org.junit.internal.runners.statements.RunAfters
|   263 | runLeaf                 in org.junit.runners.ParentRunner
|    68 | runChild . . . . . . .  in org.junit.runners.BlockJUnit4ClassRunner
|    47 | runChild                in     ''
|   231 | run . . . . . . . . . . in org.junit.runners.ParentRunner$3
|    60 | schedule                in org.junit.runners.ParentRunner$1
|   229 | runChildren . . . . . . in org.junit.runners.ParentRunner
|    50 | access$000              in     ''
|   222 | evaluate . . . . . . .  in org.junit.runners.ParentRunner$2
|   300 | run                     in org.junit.runners.ParentRunner
|   128 | runChild . . . . . . .  in org.junit.runners.Suite
|    24 | runChild                in     ''
|   231 | run . . . . . . . . . . in org.junit.runners.ParentRunner$3
|    60 | schedule                in org.junit.runners.ParentRunner$1
|   229 | runChildren . . . . . . in org.junit.runners.ParentRunner
|    50 | access$000              in     ''
|   222 | evaluate . . . . . . .  in org.junit.runners.ParentRunner$2
|   300 | run                     in org.junit.runners.ParentRunner
|   290 | doCall . . . . . . . .  in _GrailsTest_groovy$_run_closure4
|   248 | doCall                  in _GrailsTest_groovy$_run_closure2
|   195 | doCall . . . . . . . .  in _GrailsTest_groovy$_run_closure1_closure21
|   184 | doCall                  in _GrailsTest_groovy$_run_closure1
^    82 | doCall . . . . . . . .  in TestApp$_run_closure1
| Error 2013-03-05 00:05:18,657 [main] ERROR compiler.CoffeeCompiler  - Error in CoffeeScript: 
SyntaxError: In src\coffee\myBadFile.coffee, unmatched ) on line 3
    at SyntaxError (unknown source)
    at Lexer.exports.Lexer.Lexer.error (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:682:13)
    at Lexer.exports.Lexer.Lexer.pair (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:634:16)
    at Lexer.exports.Lexer.Lexer.literalToken (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:456:16)
    at Lexer.exports.Lexer.Lexer.tokenize (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\lexer.js:33:220)
    at Object.exports.compile.compile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\coffee-script.js:47:32)
    at compileScript (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:182:33)
    at fs.stat.notSources.(anonymous function) (C:\Users\Administrator\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:152:18)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
 in src\coffee\myBadFile.coffee
| Running 14 integration tests... 5 of 14
--Output from testCompileFile--
| Running 14 integration tests... 6 of 14
--Output from testMultipleCoffeeSourceTrees--
| Running 14 integration tests... 7 of 14
--Output from testCoffeeSourceTreeIgnoresHiddenPaths--
| Running 14 integration tests... 8 of 14
--Output from testDefaultConfig--
| Error 2013-03-05 00:05:23,233 [pool-12-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\testDefaultConfig.coffee
| Running 14 integration tests... 9 of 14
--Output from testWithConfig--
| Error 2013-03-05 00:05:24,246 [pool-13-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\testWithConfig.coffee
| Running 14 integration tests... 10 of 14
--Output from testCoffeeSourceTree--
| Error 2013-03-05 00:05:25,261 [pool-14-thread-3] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\testCoffeeSourceTree1.coffee
| Error 2013-03-05 00:05:25,264 [pool-14-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\child\subchild\testCoffeeSourceTree3.coffee
| Error 2013-03-05 00:05:25,266 [pool-14-thread-2] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\child\testCoffeeSourceTree2.coffee
| Running 14 integration tests... 11 of 14
--Output from testInvalidCoffeeScript--
| Error 2013-03-05 00:05:26,783 [main] ERROR compiler.CoffeeCompiler  - null in src\coffee\myBadFile.coffee
| Running 14 integration tests... 12 of 14
--Output from testCompileFile--
| Error 2013-03-05 00:05:26,795 [main] ERROR compiler.CoffeeCompiler  - null in src\coffee\testCompileFile.coffee
| Failure:  testCompileFile(coffeescript.compiler.PluginTestWithRhinoTests)
|  ro.isdc.wro.WroRuntimeException
    at org.grails.plugins.coffee.compiler.CoffeeCompiler.compileFile(CoffeeCompiler.groovy:87)
    at org.grails.plugins.coffee.compiler.CoffeeCompilerManager.compileFileFromConfig(CoffeeCompilerManager.groovy:67)
    at coffeescript.compiler.PluginTestWithRhinoTests.testCompileFile(PluginTestWithRhinoTests.groovy:167)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
    at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
    at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:114)
    at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
    at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
    at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1130)
    at java.beans.Introspector.getBeanInfo(Introspector.java:414)
    at java.beans.Introspector.getBeanInfo(Introspector.java:161)
    at org.grails.plugins.coffee.compiler.processor.RhinoCoffeeScriptProcessor.<init>(RhinoCoffeeScriptProcessor.groovy:23)
    at org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor$1.initialize(CoffeeScriptProcessor.groovy:109)
    at ro.isdc.wro.util.LazyInitializer.get(LazyInitializer.java:32)
    at ro.isdc.wro.model.resource.processor.decorator.LazyProcessorDecorator.getProcessorDecorator(LazyProcessorDecorator.java:43)
    at ro.isdc.wro.model.resource.processor.decorator.LazyProcessorDecorator.process(LazyProcessorDecorator.java:54)
    at org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor.process(CoffeeScriptProcessor.groovy:77)
    at org.grails.plugins.coffee.compiler.CoffeeCompiler.compileFile(CoffeeCompiler.groovy:68)
    ... 2 more

null
ro.isdc.wro.WroRuntimeException
    at org.grails.plugins.coffee.compiler.CoffeeCompiler.compileFile(CoffeeCompiler.groovy:87)
    at org.grails.plugins.coffee.compiler.CoffeeCompilerManager.compileFileFromConfig(CoffeeCompilerManager.groovy:67)
    at coffeescript.compiler.PluginTestWithRhinoTests.testCompileFile(PluginTestWithRhinoTests.groovy:167)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
    at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
    at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:114)
    at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
    at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
    at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1130)
    at java.beans.Introspector.getBeanInfo(Introspector.java:414)
    at java.beans.Introspector.getBeanInfo(Introspector.java:161)
    at org.grails.plugins.coffee.compiler.processor.RhinoCoffeeScriptProcessor.<init>(RhinoCoffeeScriptProcessor.groovy:23)
    at org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor$1.initialize(CoffeeScriptProcessor.groovy:109)
    at ro.isdc.wro.util.LazyInitializer.get(LazyInitializer.java:32)
    at ro.isdc.wro.model.resource.processor.decorator.LazyProcessorDecorator.getProcessorDecorator(LazyProcessorDecorator.java:43)
    at ro.isdc.wro.model.resource.processor.decorator.LazyProcessorDecorator.process(LazyProcessorDecorator.java:54)
    at org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor.process(CoffeeScriptProcessor.groovy:77)
    at org.grails.plugins.coffee.compiler.CoffeeCompiler.compileFile(CoffeeCompiler.groovy:68)
    ... 2 more

| Running 14 integration tests... 13 of 14
--Output from testMultipleCoffeeSourceTrees--
| Error 2013-03-05 00:05:26,826 [pool-15-thread-3] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\testMultipleCoffeeSourceTrees1.coffee
| Error 2013-03-05 00:05:26,828 [pool-15-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\child\subchild\testMultipleCoffeeSourceTrees3.coffee
| Error 2013-03-05 00:05:26,831 [pool-15-thread-2] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\child\testMultipleCoffeeSourceTrees2.coffee
| Error 2013-03-05 00:05:26,836 [pool-16-thread-3] ERROR compiler.CoffeeCompiler  - null in src\coffee\spec\testMultipleCoffeeSourceTrees4.coffee
| Error 2013-03-05 00:05:26,838 [pool-16-thread-2] ERROR compiler.CoffeeCompiler  - null in src\coffee\spec\child\testMultipleCoffeeSourceTrees5.coffee
| Error 2013-03-05 00:05:26,840 [pool-16-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\spec\child\subchild\testMultipleCoffeeSourceTrees6.coffee
| Running 14 integration tests... 14 of 14
--Output from testCoffeeSourceTreeIgnoresHiddenPaths--
| Error 2013-03-05 00:05:28,953 [pool-17-thread-2] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\child\testCoffeeSourceTree2.coffee
| Error 2013-03-05 00:05:28,955 [pool-17-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\child\subchild\testCoffeeSourceTree3.coffee
| Error 2013-03-05 00:05:28,958 [pool-17-thread-3] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\testCoffeeSourceTree1.coffee
| Completed 14 integration tests, 1 failed in 16791ms
| Running 9 spock tests...
| Running 9 spock tests... 1 of 9
--Output from test that compiler will wrap with call method by default--
| Error 2013-03-05 00:05:30,632 [pool-18-thread-1] ERROR compiler.CoffeeCompiler  - null in web-app\js\app\testWithConfig.coffee
| Failure:  test that compiler will wrap with call method by default(coffeescript.compiler.PluginSpec)
|  Condition not satisfied:

javascriptFile.text.contains("call")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.test that compiler will wrap with call method by default(PluginSpec.groovy:41)

Condition not satisfied:

javascriptFile.text.contains("call")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

Condition not satisfied:

javascriptFile.text.contains("call")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.test that compiler will wrap with call method by default(PluginSpec.groovy:41)

| Running 9 spock tests... 2 of 9
--Output from test that nowrap causes compiler to not wrap coffeescript in call method--
| Error 2013-03-05 00:05:31,679 [pool-19-thread-1] ERROR compiler.CoffeeCompiler  - null in web-app\js\app\testWithConfig.coffee
| Failure:  test that nowrap causes compiler to not wrap coffeescript in call method(coffeescript.compiler.PluginSpec)
|  Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.test that nowrap causes compiler to not wrap coffeescript in call method(PluginSpec.groovy:72)

Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.test that nowrap causes compiler to not wrap coffeescript in call method(PluginSpec.groovy:72)

| Running 9 spock tests... 3 of 9
--Output from use same coffees and javascript folders--
| Error 2013-03-05 00:05:32,695 [pool-20-thread-1] ERROR compiler.CoffeeCompiler  - null in web-app\js\app\testWithConfig.coffee
| Failure:  use same coffees and javascript folders(coffeescript.compiler.PluginSpec)
|  Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.use same coffees and javascript folders(PluginSpec.groovy:101)

Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.use same coffees and javascript folders(PluginSpec.groovy:101)

| Running 9 spock tests... 4 of 9
--Output from ensure older js files are overridden--
| Error 2013-03-05 00:05:33,712 [pool-21-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\testWithConfig.coffee
| Failure:  ensure older js files are overridden(coffeescript.compiler.PluginSpec)
|  Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.ensure older js files are overridden(PluginSpec.groovy:130)

Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.ensure older js files are overridden(PluginSpec.groovy:130)

| Running 9 spock tests... 5 of 9
--Output from ensure newer js files aren't overridden--
| Running 9 spock tests... 6 of 9
--Output from ensure newer js files are overridden by default--
| Error 2013-03-05 00:05:35,748 [pool-23-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\testWithConfig.coffee
| Failure:  ensure newer js files are overridden by default(coffeescript.compiler.PluginSpec)
|  Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.ensure newer js files are overridden by default(PluginSpec.groovy:188)

Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

Condition not satisfied:

javascriptFile.text.contains("someFunctionCall")
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.ensure newer js files are overridden by default(PluginSpec.groovy:188)

| Running 9 spock tests... 7 of 9
--Output from set the purgeJS flag to false and ensure files stay in tact--
| Error 2013-03-05 00:05:36,766 [pool-24-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\testWithConfig.coffee
| Running 9 spock tests... 8 of 9
--Output from set the purgeJS flag to true and ensure files are purged--
| Error 2013-03-05 00:05:37,789 [pool-25-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\testWithConfig.coffee
| Failure:  set the purgeJS flag to true and ensure files are purged(coffeescript.compiler.PluginSpec)
|  Condition not satisfied:

javascriptFile.text.contains('someFunctionCall')
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.set the purgeJS flag to true and ensure files are purged(PluginSpec.groovy:242)

Condition not satisfied:

javascriptFile.text.contains('someFunctionCall')
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

Condition not satisfied:

javascriptFile.text.contains('someFunctionCall')
|              |    |
|              ""   false
web-app\js\app\testWithConfig.js

    at coffeescript.compiler.PluginSpec.set the purgeJS flag to true and ensure files are purged(PluginSpec.groovy:242)

| Running 9 spock tests... 9 of 9
--Output from test invalid coffees file--
| Error 2013-03-05 00:05:38,807 [main] ERROR compiler.CoffeeCompiler  - null in src\coffee\myBadFile.coffee
| Completed 9 spock tests, 6 failed in 8298ms
| Tests FAILED  - view reports in C:\Developer\Projects\Personal\coffeescript-compiler\target\test-reports
Disconnected from the target VM, address: '127.0.0.1:63942', transport: 'socket'

Process finished with exit code 1
```

**Comment by brian428** [comment]
Also just to be sure everything is the same between us, this is JDK 7u10 64-bit and Grails 2.2.0.

**Comment by brian428** [comment]
Finally, let me know if it would help at all for me to commit what I've got locally into a branch, if you think seeing exactly what I've got might reveal anything.

**Comment by ctoestreich** [comment]
Looks like I squashed from the wrong head branch.  I will fix tomorrow.  I am on jdk 1.6.  Will try 1.7.  The tests were not erased i simply moved the tests to a base class.  Might have gotten eaten in the bad squash.

**Pull request closed without merging**
