### PR TITLE
Adding changes for configuration options and cleaning up code

### PR DESCRIPTION
**Pull request by ctoestreich**
- Adding support for wrapJS flag to turn on or off .call() wraper
- Adding support for purgeJS flag to tell the plugin to not wack the JS on startup (sometimes useful for when items are in a shared directory with non-coffee js files.
- Adding support for overrideJS flag to allow users to not override the js file from coffee when js is newer during startup.  Useful sometimes to debug if the coffee can't quite be worked out and person needs to work in js directly while debugging.
- Adding several integration specs to test these new changes.
- Ensured that both Node and Rhino processors worked (hard to test in automation - simply add `npm install coffee-script` and test then `npm remove coffee-script` and test again)
- Code cleanup

wro4j seems to lack the ability to pass in compiler flags to the coffee processors so I had to copy and augment them in the plugin.  I have asked the wro4j author for more details on this and hopefully support will be added in the future. See http://chat.stackoverflow.com/rooms/22709/wro4j.

C

### CODE REVIEW

**Comment by brian428** [comment]
Thanks! I'll take a look at this over the weekend, but sounds like good additions!

**Comment by ctoestreich** [comment]
Just things that I wanted to use in my project.  The beauty of fork and pull.  I haven't really looked into the other CS plugins as Jeff Browns seemed old and the resource one is good, but I am moving away from resources in lieu of RequireJS in my application as I find it makes things a bit more light weight even in a multi-page app.

**Comment by ctoestreich** [comment]
Sounds like Alex is going to upgrade the library to support nowrap in the future, but we are stuck on my forked version for now. :)

**Comment by ctoestreich** [comment]
Open for debate is probably making the purgeJS default to false as my files share a dir (which I assume is common).  Also setting the overrideJS to false makes the compiler skip any files that it has already compiled so as to save some time when there are a lot of files.  If the js exists and is newer, assume it has already been compiled.  Just food for thought.

**Comment by brian428** [comment]
I appreciate it. This is my first plugin and as you said, I did it just because the existing ones didn't do what I needed...it was getting old trying to set up all my CS as resources just to get them to compile, and I needed to maintain the directory structure for the compiled .js since ExtJS can load classes on demand.

**Comment by ctoestreich** [comment]
ExtJS is a framework that eats babies when not used correctly.  We use the ext grid, but if we could move away from it we would... just nothing else like it out there.  Such a heavy framework that one.  JqGrid just doesn't cut the mustard.  Granted we are still on a 3.1 release and not to mention we have to support IE6 still, upgrading to latest of anything is pretty political.  Somehow I manage to secretly build and maintain several grails applications... I have said too much! :)

**Comment by brian428** [comment]
Just out of curiosity, how does your change to log.debug work? If I set logging to debug in my Config.groovy, I obviously get a ton of debug output, but I don't see any related to the plugin. I'll go see if I can find any info on this, but if you happen to know, is there a debug setting that would enable the plugin's debug logging (and ideally, ONLY the plugin's debug logging and not all the other Grails debug output)? Thanks.

**Comment by brian428** [comment]
Ah NM I've got it (debug  'org.grails.plugins.coffee.compiler').

**Pull request closed without merging**
